### ISSUE TITLE
 Add Fast Furnace into the server side category and update Hydrogen's and Starlight's descriptions

### ISSUE THREAD

**Issue by Kizuati** [ReperakPro/fabric-optimization-mods#1]
Fast Furnace makes vanilla not recalculate furnace fuel stuff all the time and caches it instead. Also fixes a bug. Demojank'd.
https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric
Additionally,update Hydrogen's description - it's much more stable now and is out of alpha into a stable enough beta.
Starlight is also still in Beta and can cause issues,but is stable-ish. Reflect that in the description.

**Comment by ReperakPro** [comment]
Fast Furnace will not be added due to inactivity, but the descriptions and stability ratings have been fixed.

**Comment by DragonEggBedrockBreaking** [comment]
Also, I believe FastFurnace was merged into Fabric API.

**Comment by Brottweiler** [comment]
>Fast Furnace will not be added due to inactivity
@ReperakPro FastFurnace was updated yesterday.

**Comment by DragonEggBedrockBreaking** [comment]
> @ReperakPro FastFurnace was updated yesterday.
Oh, yes, I am so stupid, I am the one who  updated the mod... I am so stupid...
