### ISSUE TITLE
Mod Request: Cull Particles Fabric

### ISSUE THREAD

**Issue by Brottweiler** [ReperakPro/fabric-optimization-mods#14]
**Requirements for a mod to be added:**
- [x] The mod must be open-source. 
- [x] The mod cannot sacrifice vanilla behavior for performance.
- [x] The mod must be actively maintained.

**Mod name:** Cull Particles Fabric

**Type of mod (e.g. rendering, lighting, extra):** rendering

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/Tfarcenim/CullParticlesFabric

**Developer/organization:** tfarecnim

**Additional notes:**
Curseforge link: https://www.curseforge.com/minecraft/mc-mods/cull-particles-fabric

**Comment by NebelNidas** [comment]
Does this enhance performance when Sodium is installed? Because on the comments of the old gist, someone said Sodium would this mod redundant

**Comment by Brottweiler** [comment]
> Does this enhance performance when Sodium is installed? Because in the comments of the old gist, someone said Sodium would make this mod redundant
> 
> Edit: Yes, Sodium really makes this mod redundant:

Interesting, did not know that. Yes, then it seems like this is redundant.

**Comment by DragonEggBedrockBreaking** [comment]
Why was this closed? Some people may still want this if they use canvas rather than sodium. Not every client mod assumes sodium is used.

**Comment by Brottweiler** [comment]
Good point.

**Comment by ReperakPro** [comment]
99190d4
