### ISSUE TITLE
Mod Request: FastChest

### ISSUE THREAD

**Issue by Brottweiler** [ReperakPro/fabric-optimization-mods#15]
**Requirements for a mod to be added:**
- [x] The mod must be open-source. 
- [x] The mod cannot sacrifice vanilla behavior for performance.
- [x] The mod must be actively maintained.

**Mod name:** FastChest

**Type of mod (e.g. rendering, lighting, extra):** rendering

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/FakeDomi/FastChest

**Developer/organization:** FakeDomi

**Additional notes:**
Makes chests static blocks instead of tile entities.
I hope that the mod doesn't sacrifice vanilla behaviour. What will happen is that the lid on the chest won't open. I think this is a valid compromise.
Curseforge link: https://www.curseforge.com/minecraft/mc-mods/fastchest

**Comment by DragonEggBedrockBreaking** [comment]
Should be closed as it sacrifices vanilla behaviour- EnhancedBlockEntities doesn't.

**Comment by DragonEggBedrockBreaking** [comment]
> Should be closed as it sacrifices vanilla behaviour- EnhancedBlockEntities doesn't.

See #4
