### ISSUE TITLE
Mod Request: EntityCulling-Fabric

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [ReperakPro/fabric-optimization-mods#3]
**Mod name:** EntityCulling-Fabric

**Type of mod:** Rendering?

**Repository:** https://github.com/tr7zw/EntityCulling-Fabric

**Developer/organization:** tr7zw

**Additional notes:**
There are some small weird issues, especially with bigger mobs like withers, but they have been more or less fixed in the newer branch [naiveHitboxTracing](https://github.com/tr7zw/EntityCulling-Fabric/tree/naiveHitboxTracing) (which will be published soon).

**Comment by xpopy** [comment]
Should be noted that it has a max distance of 64 blocks, after which it hides all entities. This pretty much breaks the Entity Distance setting. (for now)

**Comment by DragonEggBedrockBreaking** [comment]
On second thoughts, sodium also breaks transparency and stuff, and since it is a bug and does not *intentionally modify vanilla*, I'm assuming it will be okay to include. I will re-open this, and Reperak can decide what to do.

**Comment by ReperakPro** [comment]
There doesn't seem to be any documentation on this mod, which is a bit worrying. If you can provide a small benchmark (probably randomly spread mobs with some off camera) of with and without the mod, and it provides a fair enough performance advantage, then I'll include it.

**Comment by DragonEggBedrockBreaking** [comment]
> There doesn't seem to be any documentation on this mod, which is a bit worrying. If you can provide a small benchmark (probably randomly spread mobs with some off camera) of with and without the mod, and it provides a fair enough performance advantage, then I'll include it.

Ok, I have school now, but I can do this later.

**Comment by DragonEggBedrockBreaking** [comment]
Ok, here.

**Without the mod:**
https://gph.is/g/ZPGkA0k

**With the mod:**
https://gph.is/g/apWq7lO

Note that this is with the special hitbox tracing branch (which will soon be merged into master). The performance is the same, but the master branch has a couple of weird bugs.

**Comment by ReperakPro** [comment]
Added.

**Comment by DragonEggBedrockBreaking** [comment]
> On second thoughts, sodium also breaks transparency and stuff, and since it is a bug and does not _intentionally modify vanilla_, I'm assuming it will be okay to include. I will re-open this, and Reperak can decide what to do.

As I expected, the author is already working on fixing this.
