### ISSUE TITLE
Mod Request: Iris Shaders

### ISSUE THREAD

**Issue by mr-pi12** [ReperakPro/fabric-optimization-mods#37]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** Iris Shaders

**Type of mod (e.g. rendering, lighting, extra):**  Lighting - shaders mod

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/IrisShaders/Iris 

**Developer/organization:** coderbot16

**Additional notes:**
Is compatible with existing optifine shaders, unlike canvas and has superior performance to optifine due to the optimizations included in sodium, which is bundled with this mod. Is also compatible with starlight or phosphor, which can also be used to help chunk loading times and performance. Iris is still in development and though all optifine shaders are supported, glitches and bugs are common.

**Comment by ReperakPro** [comment]
This is not an optimization mod.

**Comment by DragonEggBedrockBreaking** [comment]
Iris adds entity culling optimisations to make entity shadows perform better, so sodium + iris (without shadows) can give you more fps than just sodium

**Comment by mr-pi12** [comment]
> This is not an optimization mod.

Neither is sodium extra? Canvas also acts as a shader mod, not an optimization mod, but iris is a shader mod that strives for performance and compatibility. It's not perfect, but it performs extremely well, and like dragonegg says, it does offer a little better performance than sodium. If you added visual mods like sodium extra, shouldn't this also be added? It's beneficial for users who don't want to use optifine but still want the same shaders. Iris has up to 25% performance boost over optifine shaders too.

**Comment by ReperakPro** [comment]
> Iris adds entity culling optimisations to make entity shadows perform better, so sodium + iris (without shadows) can give you more fps than just sodium

Iris also completely ruins entity rendering (no AO or shadows)

> > This is not an optimization mod.
> 
> Neither is sodium extra? Canvas also acts as a shader mod, but not an optimization mod, but iris is a shader mod that strives for performance and compatibility.

Sodium Extras and Iris are two completely different mods, and while neither are explicitly optimization mods, Sodium Extras is more fitting of its spot on the list, in the extra section. As for Canvas, its "shaders" are meant for mod developers to add bloom and other post-processing effects to their textures.

I don't entirely trust Iris as an "optimization mod" on its own.

**Comment by mr-pi12** [comment]
> Iris also completely ruins entity rendering (no AO or shadows)

By AO do you mean ambient occlusion?
I'm also sure that iris does have entity shadows, I use the 1.17.1 version and they seem to work fine

**Comment by ReperakPro** [comment]
> By AO do you mean ambient occlusion?
> I'm also sure that iris does have entity shadows, I use the 1.17.1 version and they seem to work fine

Ah, they fixed that? Nice, though I still can't advocate for running an entire shaders mod for a very small performance increase at best. Hopefully this is understandable.

**Comment by mr-pi12** [comment]
Yeah, it's fine. I'm sure it'll get better over the course of this year, it does describe itself as a wip. I think it's less about the performance increase than it is about being a substitute for optifine shaders.

**Comment by mr-pi12** [comment]
There's this mod that implements another optifine feature from the shaders section - resolution control+ (changes render resolution), but I don't want to open an issue for it because it sacrifices visuals for performance.

**Comment by mr-pi12** [comment]
> Ah, they fixed that? Nice, though I still can't advocate for running an entire shaders mod for a very small performance increase at best. Hopefully this is understandable.

Maybe it could be marked as an extras mod instead?

**Comment by mr-pi12** [comment]
> I still can't advocate for running an entire shaders mod for a very small performance increase at best.

The websites also claims to have _up to_ 60% improvement in entity rendering and improvements in shadow rendering performance. I don't know how much of an effect these optimizations have for an average user.
