### ISSUE TITLE
Mod Request: Entity Distance

### ISSUE THREAD

**Issue by mr-pi12** [ReperakPro/fabric-optimization-mods#39]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** Entity Distance

**Type of mod (e.g. rendering, lighting, extra):** rendering (probably)

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/capnkork/entity-distance

**Developer/organization:** capnkork

**Additional notes:**
This is one mod I'm skeptical about, but found on another mod optimization list (of both fabric and forge mods (link here: https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88)) and I haven't tested it yet. I'd assume it's similar to sodium's entity render distance feature, but the distance can be customised? If so, people who use canvas could use it, I suppose.

**Comment by DragonEggBedrockBreaking** [comment]
This does not keep parity with vanilla behaviour

**Comment by mr-pi12** [comment]
Is this feature not also in sodium though?

**Comment by DragonEggBedrockBreaking** [comment]
No. There is a slider for this in the sodium video settings menu because this is sort of a vanilla feature, this mod just extends it, while breaking vanilla parity somewhat.

**Comment by mr-pi12** [comment]
Ah, right. I was thinking under the lines of canvas users being able to use this if they wanted to improve performance a little

**Comment by ReperakPro** [comment]
Closing with @DragonEggBedrockBreaking's point
