### ISSUE TITLE
Mod Request: Enhanced Block Entities

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [ReperakPro/fabric-optimization-mods#4]
**Mod name:** Enhanced Block Entities

**Type of mod:** Rendering?

**Repository:** https://github.com/FoundationGames/EnhancedBlockEntities

**Developer/organization:** FoundationGames

**Additional notes:**
Incompatible with sodium - requires indium. I believe it is fine with canvas, so that's why I suggested it.

This does **NOT** sacrifice vanilla behaviour. Unlike FastChest, chest animations are **NOT** removed.

**Comment by DragonEggBedrockBreaking** [comment]
Update: The pull request to fix the EnhancedBlockEntities compatibility has been merged into sodium.

It may require FRAPI, but I am not 100% sure, so maybe list sodium as a *possible incompatibility*?

**Comment by NebelNidas** [comment]
If anyone proposes [FastChest](https://www.curseforge.com/minecraft/mc-mods/fastchest) in the future, link them to here because this mod does the same (only that FastChest disables animations and EBE does not, thus making the latter superior)

**Comment by ReperakPro** [comment]
Added in c6c84a8
