### ISSUE TITLE
Mod Request: Clumps

### ISSUE THREAD

**Issue by mr-pi12** [ReperakPro/fabric-optimization-mods#40]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** Clumps

**Type of mod (e.g. rendering, lighting, extra):** Rendering

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/jaredlll08/Clumps

**Developer/organization:** jaredlll08

**Additional Notes**
It just combines multiple xp orbs into one entity, really, not much to say. Fat experience orbs does the same thing, I think.

**Comment by Brottweiler** [comment]
1.17 changelog
```
- Now sometimes merge when in large quantities, to improve performance.
  - Merging does not affect the amount of experience gathered from collecting the merged orbs.
```
https://minecraft.fandom.com/wiki/Java_Edition_1.17#Non-mob_entities

But maybe Clumps is more aggressive? 

There's also the [Fat Experience Orbs](https://www.curseforge.com/minecraft/mc-mods/fat-experience-orbs) mod.

**Comment by ReperakPro** [comment]
> The mod cannot sacrifice vanilla behavior for performance.

I would consider this sacrificing behavior.

**Comment by mr-pi12** [comment]
> > The mod cannot sacrifice vanilla behavior for performance.
> 
> I would consider this sacrificing behavior.

Agreed, I'll open a fat experience orbs request instead.

**Comment by DragonEggBedrockBreaking** [comment]
Wasn’t this already partially added in 1.17 vanilla?

**Comment by mr-pi12** [comment]
>Wasn’t this already partially added in 1.17 vanilla? I remember gnembon made a video that relied on that feature for lag-proofing.

Yeah, it's been added, but I don't know how much of a performance change there is between 1.16 and 1.17 - the changelog states that it "sometimes" does this
