### ISSUE TITLE
Mod Request: Better Beds

### ISSUE THREAD

**Issue by NebelNidas** [ReperakPro/fabric-optimization-mods#5]
**Mod name:** Better Beds

**Type of mod:** Rendering

**Repository:** https://github.com/TeamMidnightDust/BetterBeds

**Developer/organization:** MidnightDust

**Additional notes:**
- Incompatible with [Bedspreads](https://www.curseforge.com/minecraft/mc-mods/bedspreads-fabric)
- For more info, see the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/better-beds)

**Comment by DragonEggBedrockBreaking** [comment]
Can confirm, there is a large performance improvement when around many beds.

**Comment by ReperakPro** [comment]
Added.

**Comment by mr-pi12** [comment]
Was this removed for the same reason as cull leaves?
