### ISSUE TITLE
Mod Request: Cull Leaves

### ISSUE THREAD

**Issue by NebelNidas** [ReperakPro/fabric-optimization-mods#7]
**Mod name:** Cull Leaves

**Type of mod** Rendering

**Repository:** https://github.com/TeamMidnightDust/CullLeaves

**Developer/organization:** MidnightDust

**Additional notes:**
- OK, it sacrifices a **bit** of vanilla visuals by only rendering the front (optionally also the back) textures of leaf blocks, but I think that's within the bounds of what should be acceptable. Optifine has the same functionality.
- CurseForge page: https://www.curseforge.com/minecraft/mc-mods/cull-leaves

**Comment by DragonEggBedrockBreaking** [comment]
That should not be within bounds of what is acceptable. Leaves look ugly. Don't include this @ReperakPro

**Comment by NebelNidas** [comment]
@DragonEggBedrockBreaking That's obviously subjective, and since Optifine has this, many people coming from it are expecting similar functionality. Just include a warning, that should be enough.

**Comment by DragonEggBedrockBreaking** [comment]
> That's obviously subjective, and since Optifine has this, many people coming from it are expecting similar functionality. Just include a warning, that should be enough.

1) "OptiFine has this" OptiFine is NOT a performance mod (any more). It simply loads less chunks and uses placebo toggles to make you think your game is better. OptiFine is not a comparison.

2) Why would people expect the same functionality? I believe the main thing about OptiFine smart leaves is that leaves look better when using fast graphics, but this mod does not change their appearance when using that.

You points are completely invalid.

**Comment by NebelNidas** [comment]
1. While Optifine also has purely cosmetic options, it still is a performance enhancing mod.
2. Cull Leaves improves performance, that's the whole point of this mod request. It' the perfect middle ground between Fast and Fancy graphics for some users.

**Comment by DragonEggBedrockBreaking** [comment]
>     1. While Optifine also has purely cosmetic options, it still is a performance enhancing mod.

It loads less chunks to gain fps. This means it sacrifices visuals. You can force-render these chunks (so it is like vanilla) using optifine zoom, but fps drops to vanilla. It is not a performance mod in newer versions. It is better in 1.8, 1.12, etc. though.

>     2. Cull Leaves improves performance, that's the whole point of this mod request. It's the perfect middle ground between Fast and Fancy graphics for some users.

It improves performance, but sacrifices visuals. That is my entire point.

**Comment by DragonEggBedrockBreaking** [comment]
Update: after playing around with this mod in an actual minecraft world, i barely noticed the difference will cull leaves, and neither would 99% of players. The visual difference is only realy noticable when you benchmark a giant chunk of leaves, which is not really a realistic scenario. **NOTE: This is only relevant if you enable the inbuilt resource pack; without it, leaves look like shit**

**Comment by ReperakPro** [comment]
I'll make an exception for this, as the visual differences aren't serious, and it has the potential to help on specific GPUs. Added.

**Comment by mr-pi12** [comment]
Was this added, I can't see it in the list.

**Comment by ReperakPro** [comment]
> Was this added, I can't see it in the list.

This was removed a while back

**Comment by mr-pi12** [comment]
> This was removed a while back

Why did you remove it? Is it because it changes how the game looks?

**Comment by ReperakPro** [comment]
> Why did you remove it? Is it because it changes how the game looks?

Yes and also because it didn't prove any meaningful performance increase.
