### ISSUE TITLE
Mod Request: Smooth Boot

### ISSUE THREAD

**Issue by NebelNidas** [ReperakPro/fabric-optimization-mods#8]
**Mod name:** Smooth Boot

**Type of mod** start-up

**Repository:** https://github.com/UltimateBoomer/mc-smoothboot

**Developer/organization:** UltimateBoomer

**Additional notes:**
- Compatible with LazyDFU (should also be compatible with Cadmium?)
- By itself it still loads DFU, but in combination with the aforementioned it doesn't
- Even when used with the mods mentioned above, it still makes Minecraft hang less due to better thread-management (thread count and priority)
- CurseForge page: https://www.curseforge.com/minecraft/mc-mods/smooth-boot

**Comment by DragonEggBedrockBreaking** [comment]
- It reduces performance for many minutes after launch
- It is not compatible with LazyDFU, since LazyDFU removes the thing that smoothboot optimises
- Therefore, it is literally just LazyDFU but not as good and detrimental to performance

**Comment by NebelNidas** [comment]
@DragonEggBedrockBreaking No, it's not.
- It doesn't reduce performance. It just offloads work to separate threads, which **may** still run after the game has started, but nevertheless it makes start-up smoother. 
- Yes, start-up might be slower on low-end machines, but it makes start-up **smoother** (hence the name). Meaning: While it might take longer to start up, Minecraft won't hang as much or potentially even crash.
- LazyDFU and SmoothBoot are 100% compatible to one-another:
  - https://github.com/UltimateBoomer/mc-smoothboot/wiki#compability
  - https://github.com/astei/lazydfu#smooth-boot
- While yes, the biggest boost SmoothBoot gives becomes irrelevant while using LazyDFU, it still has better thread-management which makes Minecraft hang less in the start-up phase (as described above).

**Comment by DragonEggBedrockBreaking** [comment]
> It doesn't reduce performance. It just offloads work to separate threads, which **may** still run after the game has started, but nevertheless it makes start-up smoother.

Literally everyone who has talked about it has said that it reduces fps by like 80% for the first 5 or so minutes after startup. This *is* measurable.

>     * Yes, start-up might be slower on low-end machines, but it makes start-up **smoother** (hence the name). Meaning: While it might take longer to start up, Minecraft won't hang as much or potentially even crash.

DFU is the main cause of that and with LazyDFU, hanging and crashing is practically gone, even on my low-end laptop.

>     * While yes, the biggest boost SmoothBoot gives becomes irrelevant while using LazyDFU, it still has better thread-management which makes Minecraft hang less in the start-up phase (as described above).

As I already said, LazyDFU gives the same improvement, in a different way.

**Comment by NebelNidas** [comment]
> Literally everyone who has talked about it has said that it reduces fps by like 80% for the first 5 or so minutes after startup. This is measurable.

I want to see benchmarks for that, it isn't noticeable on my hardware.

> DFU is the main cause of that and with LazyDFU, hanging and crashing is practically gone, even on my low-end laptop.

Yep, it's the main cause, but Smooth Boot still optimises the rest, which makes it less noticeable, but better than LazyDFU-only nonetheless.

**Comment by DragonEggBedrockBreaking** [comment]
> Yep, it's the main cause, but Smooth Boot still optimises the rest, which makes it less noticeable, but better than LazyDFU-only nonetheless.

Can you please explain what is 'the rest'? I have never heard this part before, so I don't know much about this...

**Comment by ReperakPro** [comment]
When I moved the list to this repository, I removed Smooth Boot due to its performance issues. Closed.

**Comment by NebelNidas** [comment]
Sorry for the late response.

> Can you please explain what is 'the rest'? I have never heard this part before, so I don't know much about this...

See here:
- https://github.com/UltimateBoomer/mc-smoothboot/wiki
- https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16

As already said above, it has no performance improvements when used with LazyDFU, but it still
> stops Minecraft from lagging other programs that are running at the same time (ex. Youtube videos), while it does not have a large impact on the actual game performance

(`large impact` in the meaning of `performance improvements`, otherwise the benchmarks wouldn't indicate a small improvement: https://github.com/UltimateBoomer/mc-smoothboot/wiki/Benchmarks)

<br>

If you read the wiki pages I linked above, you will stumble upon this sentence: 
> ... may have an impact on in-game performance.

So I asked whether this means negative effects, and got this answer: https://github.com/UltimateBoomer/mc-smoothboot/issues/16#issuecomment-798929137

So in general: No, it will not slow down the game, it only limits the thread count for processes which don't need many threads anyway. See the benchmarks: Even in AOF3 with 160+ mods it has no negative implications, only positive ones.

**Comment by DragonEggBedrockBreaking** [comment]
> stops Minecraft from lagging other programs that are running at the same time (ex. Youtube videos), while it does not have a large impact on the actual game performance

LazyDFU does the same thing due to the performance impact on the game itself being reduced and therefore reducing CPU usage. i.e. LazyDFU does this as a byproduct of removing DFU.

> So in general: No, it will not slow down the game

He is saying that the stutters for him are minor, but in my testing, and in testing of many people who I know better and trust better, the performance impact is significant.

In addition to this, why add SmoothBoot, when LazyDFU is better *and* doesn't give *any* extra stutters, except from when upgrading a world, which can be avoided with `optimise world` anyway.

**Comment by NebelNidas** [comment]
> LazyDFU does the same thing due to the performance impact on the game itself being reduced and therefore reducing CPU usage. i.e. LazyDFU does this as a byproduct of removing DFU.

How often do I have to repeat this? LazyDFU **only** prevents the DFU from loading, SmoothBoot on the other hand also improves the thread-priority management:
![github com_UltimateBoomer_mc-smoothboot_wiki_Configuration_-Fabric-1 16 (1)](https://user-images.githubusercontent.com/48808497/114017727-a827c280-986c-11eb-9f29-9e81ae893df3.png)

![github com_UltimateBoomer_mc-smoothboot_wiki_Configuration_-Fabric-1 16](https://user-images.githubusercontent.com/48808497/114017624-8a5a5d80-986c-11eb-98b3-89d39f2fdd43.png)

<hr>

> He is saying that the stutters for him are minor, but in my testing, and in testing of many people who I know better and trust better, the performance impact is significant.

Stutters would only occur during resource loading, so when
> some loading tasks [run] in game, or some mods [...] use this executor to run stuff.

This almost never happens, but even when it does, it's better to slow down the game a bit than to overload your system/CPU resulting in a hanging PC (rather than only the game) and eventually a "Minecraft is not responding" message. Which do you prefer?
